appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: oZhB5mUMWJPYIW1sUBOZwmNRiAiQVhf+A6Rgk+Kbq72kky7sEqCPZ8hzVwZIBAAwRiGbqcDdIA3GB9ke+hz0V73rfsbFv9WHtL9u4PuzGBdh71JafImgbkoxOxSpCFJ6Ga3nZZc/BGGRP+zn/Ip+jGyA0iLSaC8lkRiI6UcEXAxQqLdzhFulECo9TeJ4sG76QsA/H8SPWHtG1JmLJMRzJbQmv760r3cPbC2tCazPmbtp51NCJZlSk8H2Uwig9PoGM98XJ/WCOPIA4tWwadAQiTwPQaIDcqXPNjRwFXOeGy4BJMuBewqFVYqP5Z8gVnNpeg2kpamORs4OVhVn0O7cv479E9u3fxkrV3Cp6V89rCng9n83mT0stoj7RyH8Lygufb4VHuxh5emgcqoh2EfbC6Ey+odCth5+Cz5z8A9eX/AKx8h5WOruL7cHdj5LAv2Y4ZpFTpwFBrKekGhmJPqIb8rJDLfUaTUNi7yUptwMaMxfBU0QDcA/zoD4k4FlszZpIpom3WDXI/h0Zh6cO34s9wAqYPWjqcImUaI0cqcw3mgas6tVzt006STyXsic7GJ/rAaawhXd8Ch5jF68+Xtb7KWl8Vbw8UvM8vtyFDtQsj8JbF6pkM48DuC6YifgIhEYknoJalmxrILiNouqhBAAPdguzfb+DVQN+IG/qh+Slr0=}
