travis:
  secure:
    BINSTAR_TOKEN: URzqaKmGgjMNCRAhEiQbFnocCaxXA/lrfy2CJG6AyP86MYPoqKz+U2QOk4rGHNANR1tZwJW2e2RIldWQeOYGVci0mlnfz0pu5aLICgozdpT/Mvj2M7+qCixzjMDIYW17kSHfiPAK+mX1iwcxYwBm1CAPgU3SwGQpkqnyAAM4RXCnww1iAnS5GlMVlwxD1BVnK9Ar0/I0wu3AJh4QXYE6Cr3PyaorpeGmwelLctLAtp8mdHPv08OPBLNkldb8Bi7lxE5fp40VE8tVnsgO1/5lJ3OvlhSz2+FPHBq00IETYHNpHd2BGU8Qc99ktbX8ONK+wcN3m1PXIkuyZwbnc6H0es+Aog+f21UsoeTI+K4Ygr9vhyDr9VK2thJwPq9gn24KaMikUuETdXWRNYisVeTl3TDkWKt9kptAjVD/WU64hdXfC1323zUx2cfpUGza65isZ1GFkqiyhofotj87+98XZ7JnvF8eDdq0mzfi3tuDEYPpb/YBO48KHswG6fzpZsRLGFQ67m0TJMzj3VT+oDPcyrmFETBcY9YYo/YMH/4KSC1qisN8xFIjp7u8DzgvKfhTBvWhQyt5R0sUGbUoft+4qIDKAx5Mg7PdFX35TBoOq1OCTnOoDk15/94G3dw/x6/uFnxugU0j0cMvK9jYch4YyfE9A9x+GE/7euVPdLap2xo=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
